<?php
require_once "TakeScreenshot.php";
require_once "config.php";

const LOEWE_PDF = 'loewe.pdf';
const LOEWE_JPG = 'loewe.jpg';
const LOEWE_SLICE_JPG = 'loeweSlice.jpg';

if (php_sapi_name() === 'cli') {

}

class GetMenuLoewe
{
    /**
     * @throws ImagickException
     */
    public function getMenu(): void
    {
        $link = 'https://www.pogastro.com/view/menu-pdf?venue=36946-restaurant-z-alten-loewen&type=daily&menu=1&template=venue_daily_newtemplate';
        if (!empty($link)) {
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL, 'https://app.pogastro.com/api/venuepublic/36946-restaurant-z-alten-loewen/print/generate-public-pdf');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"type\":\"daily\",\"menu\":\"1\",\"template\":\"venue_daily_newtemplate\",\"rest\":true,\"lang\":\"de-ch\",\"legacy\":true}");
            curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

            $headers = array();
            $headers[] = 'Sec-Fetch-Mode: cors';
            $headers[] = 'Origin: https://app.pogastro.com';
            $headers[] = 'Accept-Language: en';
            $headers[] = 'X-Requested-With: XMLHttpRequest';
            $headers[] = 'Cookie: __cfduid=d6604778e4346a9cae0629216197925561572437982; crisp-client%2Fsession%2F52fbc349-29e5-4ba3-b2df-f882b7da3208=session_2bf32eef-1db7-419b-abe9-6db4618c6054';
            $headers[] = 'Pragma: no-cache';
            $headers[] = 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36';
            $headers[] = 'Content-Type: application/json;charset=UTF-8';
            $headers[] = 'Accept: application/json, text/plain, /';
            $headers[] = 'Cache-Control: no-cache';
            $headers[] = 'Authority: app.pogastro.com';
            $headers[] = 'Referer: https://app.pogastro.com/view/menu-pdf?venue=36946-restaurant-z-alten-loewen&type=daily&menu=1&template=venue_daily_newtemplate';
            $headers[] = 'Sec-Fetch-Site: same-origin';
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close($ch);

            $url = 'https://app.pogastro.com' . $result;

            // download pdf
            $fp = fopen(MENU_PATH . LOEWE_PDF, 'w');

            // create curl resource
            $ch = curl_init();

            // set url
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
            curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Mobile Safari/537.36');
            curl_setopt($ch, CURLOPT_FILE, $fp);
            curl_exec($ch);

            // close curl resource to free up system resources
            curl_close($ch);
            fclose($fp);

            // convert to image
            $image = new Imagick();
            $image->setResolution( 300, 300 );
            $image->readImage(MENU_PATH . LOEWE_PDF);
            $image->setImageFormat( 'jpg' );
            $image->writeImage(MENU_PATH . LOEWE_JPG);

            // scale
            $imagick = new \Imagick(MENU_PATH . LOEWE_JPG);
            $imagick->scaleImage(600, 0);
            file_put_contents(MENU_PATH . LOEWE_SLICE_JPG, $imagick->getImageBlob());
        }
    }
}