<?php
require_once "TakeScreenshot.php";
require_once "config.php";

const LOEWE_PDF = 'loewe.pdf';
const LOEWE_JPG = 'loewe.jpg';
const LOEWE_SLICE_JPG = 'loeweSlice.jpg';

if (php_sapi_name() === 'cli') {
    $link = 'https://www.pogastro.com/view/menu-pdf?venue=36946-restaurant-z-alten-loewen&type=daily&menu=1&template=venue_daily_newtemplate';
    if (!empty($link)) {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://www.pogastro.com/api/venuepublic/36946-restaurant-z-alten-loewen/print/generate-public-pdf');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"type\":\"daily\",\"menu\":\"1\",\"template\":\"venue_daily_newtemplate\"}");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = [];
        $headers[] = 'Pragma: no-cache';
        $headers[] = 'Sec-Fetch-Site: same-origin';
        $headers[] = 'Origin: https://www.pogastro.com';
        $headers[] = 'Accept-Encoding: gzip, deflate, br';
        $headers[] = 'Accept-Language: en';
        $headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Mobile Safari/537.36';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Content-Type: application/json;charset=UTF-8';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'Cache-Control: no-cache';
        $headers[] = 'X-Requested-With: XMLHttpRequest';
        $headers[] = 'Connection: keep-alive';
        $headers[] = 'Referer: https://www.pogastro.com/view/menu-pdf?venue=36946-restaurant-z-alten-loewen&type=daily&menu=1&template=venue_daily_newtemplate';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            //echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        $url = 'https://www.pogastro.com' . $result;

        // download pdf
        $fp = fopen(MENU_PATH . LOEWE_PDF, 'w');

        // create curl resource
        $ch = curl_init();

        // set url
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Mobile Safari/537.36');
        curl_setopt($ch, CURLOPT_FILE, $fp);
        curl_exec($ch);

        // close curl resource to free up system resources
        curl_close($ch);
        fclose($fp);

        // convert to image
        $image = new Imagick();
        $image->setResolution( 300, 300 );
        $image->readImage(MENU_PATH . LOEWE_PDF);
        $image->setImageFormat( 'jpg' );
        $image->writeImage(MENU_PATH . LOEWE_JPG);

        // scale
        $imagick = new \Imagick(MENU_PATH . LOEWE_JPG);
        $imagick->scaleImage(800, 0);
        file_put_contents(MENU_PATH . LOEWE_SLICE_JPG, $imagick->getImageBlob());
    }
}